version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: npm run build
  test:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - run: echo "testing front end"
      - run: npm install
<<<<<<< HEAD
<<<<<<< HEAD
      - run: npm test --passWiyhNoTests
=======
      - run: npm test --passWithNoTests
>>>>>>> master
=======
      - run: npm test --passWithNoTests
>>>>>>> a7354e471d4c4ecf7461e35d27e6f503f0b3fef9
workflows:
  version: 2.1
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build